### ISSUE TITLE
usb also possible

### ISSUE THREAD

**Issue by gedw99** [stapelberg/airscan#9]
FOund here: https://openprinting.github.io/OpenPrinting-News-January-2020/#driverless-scanning

airscan SHOUD work over USB also via using https://github.com/OpenPrinting/ipp-usb
golang based :)

I dont have a USB cable to test it.  If someone has the time to test out this it be cool.

**Comment by stapelberg** [comment]
If you want to use it over USB, just run `ipp-usb` (to which you linked) and then run `airscan1`?

I don’t think we need to integrate these two projetcs any more closely. Running both seems like a fine solution.

**Comment by gedw99** [comment]
i agree.

I just did not have one of those square end usb cables that they supply with printers in order to test it.
